DATA_FOLDER = 'data/'
EXT = '.csv'

AXES = DATA_FOLDER+'axes'+EXT
COORDS = DATA_FOLDER+'coords'+EXT
VERTICES = DATA_FOLDER+'vertices'+EXT
EDGES = DATA_FOLDER+'edges'+EXT
CORNERS = DATA_FOLDER+'corners'+EXT
BOARD = DATA_FOLDER+'board'+EXT
PICKLE_FILE = DATA_FOLDER+'data.pkl'
